
campaign:

  name: "ul17_miniaod"
  label: "2017"


processes:

- name: emb
  label: $\\mu \\to \\tau$ embedded
  processes:
  - name: emb_et
  - name: emb_mt
  - name: emb_tt
  - name: emb_em

- name: dy_ll
  label: Drell-Yan ($\\ell\\ell$)
  processes:
  - name: dy_ll_m10to50
  - name: dy_ll_m50


datasets:

- name: emb_2017B_et
  process: emb_et
  key: /EmbeddingRun2017B/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017C_et
  process: emb_et
  key: /EmbeddingRun2017C/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017D_et
  process: emb_et
  key: /EmbeddingRun2017D/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017E_et
  process: emb_et
  key: /EmbeddingRun2017E/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017F_et
  process: emb_et
  key: /EmbeddingRun2017F/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017B_mt
  process: emb_mt
  key: /EmbeddingRun2017B/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017C_mt
  process: emb_mt
  key: /EmbeddingRun2017C/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017D_mt
  process: emb_mt
  key: /EmbeddingRun2017D/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017E_mt
  process: emb_mt
  key: /EmbeddingRun2017E/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017F_mt
  process: emb_mt
  key: /EmbeddingRun2017F/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017B_tt
  process: emb_tt
  key: /EmbeddingRun2017B/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017C_tt
  process: emb_tt
  key: /EmbeddingRun2017C/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017D_tt
  process: emb_tt
  key: /EmbeddingRun2017D/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017E_tt
  process: emb_tt
  key: /EmbeddingRun2017E/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017F_tt
  process: emb_tt
  key: /EmbeddingRun2017F/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017B_em
  process: emb_em
  key: /EmbeddingRun2017B/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017C_em
  process: emb_em
  key: /EmbeddingRun2017C/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017D_em
  process: emb_em
  key: /EmbeddingRun2017D/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017E_em
  process: emb_em
  key: /EmbeddingRun2017E/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: emb_2017F_em
  process: emb_em
  key: /EmbeddingRun2017F/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  dbs_instance: prod/phys03

- name: dy_ll_m10to50_madgraph
  process: dy_ll_m10to50
  key: /DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1/MINIAODSIM
  dbs_instance: prod/global

- name: dy_ll_m50_madgraph
  process: dy_ll_m50
  key: /DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM
  dbs_instance: prod/global
