config:
  name: ul17_miniaod
  aux:
    cmssw:
      release: CMSSW_10_6_28_patch1
      arch: slc7_amd64_gcc700
      custom_packages_script: ${ETV_BASE_PATH}/scripts/cmssw_packages_embedding.sh


campaign:

  name: ul17_miniaod
  aux:
    era_name: "2017"


processes:

- name: emb
  label: $\\mu \\to \\tau$ embedded
  processes:
  - name: emb_et
  - name: emb_mt
  - name: emb_tt
  - name: emb_em

- name: dy_ll
  label: Drell-Yan ($\\ell\\ell$)
  processes:
  - name: dy_ll_m10to50
  - name: dy_ll_m50


datasets:

- name: emb_2017B_et
  process: emb_et
  key: dbs/ul_embedding_rerun_puppi/Run2017B_ElTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017C_et
  process: emb_et
  key: dbs/ul_embedding_rerun_puppi/Run2017C_ElTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017D_et
  process: emb_et
  key: dbs/ul_embedding_rerun_puppi/Run2017D_ElTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017E_et
  process: emb_et
  key: dbs/ul_embedding_rerun_puppi/Run2017E_ElTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017F_et
  process: emb_et
  key: dbs/ul_embedding_rerun_puppi/Run2017F_ElTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017B_mt
  process: emb_mt
  key: dbs/ul_embedding_rerun_puppi/Run2017B_MuTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017C_mt
  process: emb_mt
  key: dbs/ul_embedding_rerun_puppi/Run2017C_MuTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017D_mt
  process: emb_mt
  key: dbs/ul_embedding_rerun_puppi/Run2017D_MuTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017E_mt
  process: emb_mt
  key: dbs/ul_embedding_rerun_puppi/Run2017E_MuTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017F_mt
  process: emb_mt
  key: dbs/ul_embedding_rerun_puppi/Run2017F_MuTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017B_tt
  process: emb_tt
  key: dbs/ul_embedding_rerun_puppi/Run2017B_TauTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017C_tt
  process: emb_tt
  key: dbs/ul_embedding_rerun_puppi/Run2017C_TauTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017D_tt
  process: emb_tt
  key: dbs/ul_embedding_rerun_puppi/Run2017D_TauTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017E_tt
  process: emb_tt
  key: dbs/ul_embedding_rerun_puppi/Run2017E_TauTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2017F_tt
  process: emb_tt
  key: dbs/ul_embedding_rerun_puppi/Run2017F_TauTau.dbs
  is_data: True
  get_dataset_metadata_callable: get_dataset_metadata_from_gc_configs
  aux:
    dbs_instance: prod/phys03
    is_emb: True

#- name: dy_ll_m10to50_madgraph
#  process: dy_ll_m10to50
#  key: /DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v1/MINIAODSIM
#  is_data: False
#  aux:
#    dbs_instance: prod/global

- name: dy_ll_m50_madgraph
  process: dy_ll_m50
  key: /DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL17MiniAODv2-106X_mc2017_realistic_v9-v2/MINIAODSIM
  is_data: False
  aux:
    dbs_instance: prod/global


channels:

- name: et
  label: $\\mathrm{{e}}\\tau_{{\\mathrm{{h}}}}$
  aux:
    triggers:
    - name: HLT_Ele27_WPTight_Gsf
    - name: HLT_Ele32_WPTight_Gsf
    - name: HLT_Ele32_WPTight_Gsf_DoubleL1EG
    - name: HLT_Ele35_WPTight_Gsf
    - name: HLT_Ele24_eta2p1_WPTight_Gsf_LooseChargedIsoPFTau30_eta2p1_CrossL1

- name: mt
  label: $\\mu\\tau_{{\\mathrm{{h}}}}$
  aux:
    triggers:
    - name: HLT_IsoMu24
    - name: HLT_IsoMu27
    - name: HLT_IsoMu20_eta2p1_LooseChargedIsoPFTau27_eta2p1_CrossL1

- name: tt
  label: $\\tau_{{\\mathrm{{h}}}}\\tau_{{\\mathrm{{h}}}}$
  aux:
    triggers:
    - name: HLT_DoubleMediumChargedIsoPFTau35_Trk1_TightID_eta2p1_Reg
    - name: HLT_DoubleTightChargedIsoPFTau35_Trk1_TightID_eta2p1_Reg
    - name: HLT_DoubleMediumChargedIsoPFTau40_Trk1_TightID_eta2p1_Reg
    - name: HLT_DoubleTightChargedIsoPFTau40_Trk1_eta2p1_Reg
