default:
  is_data: False
  process: dyjets_ll
  metadata_fetcher:
    name: DASMetadataFetcher


datasets:

- name: dyjets_ll_m50_madgraph
  metadata_fetcher:
    kwargs:
      key: /DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v1/MINIAODSIM
