config:
  name: ul16postVFP_miniaod
  aux:
    cmssw:
      release: CMSSW_10_6_28_patch1
      arch: slc7_amd64_gcc700
      custom_packages_script: ${ETV_BASE_PATH}/scripts/cmssw_packages_embedding.sh


campaign:

  name: ul16postVFP_miniaod
  aux:
    era_name: "2016postVFP"


processes:

- name: emb
  label: $\mu \to \tau$ embedded
  color1: [250, 194, 5]  # xkcd:goldenrod
  processes:
  - name: emb_et
  - name: emb_mt
  - name: emb_tt
  - name: emb_em

- name: dy_ll
  label: Drell-Yan ($\ell\ell$)
  color1: [68, 142, 228]  # xkcd:dark sky blue
  processes:
  - name: dy_ll_m10to50
  - name: dy_ll_m50


datasets:

- name: emb_2016F_et
  process: emb_et
  key: /EmbeddingRun2016_F/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016G_et
  process: emb_et
  key: /EmbeddingRun2016_G/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016H_et
  process: emb_et
  key: /EmbeddingRun2016_H/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016F_mt
  process: emb_mt
  key: /EmbeddingRun2016_F/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016G_mt
  process: emb_mt
  key: /EmbeddingRun2016_G/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016H_mt
  process: emb_mt
  key: /EmbeddingRun2016_H/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016F_tt
  process: emb_tt
  key: /EmbeddingRun2016_F/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016G_tt
  process: emb_tt
  key: /EmbeddingRun2016_G/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016H_tt
  process: emb_tt
  key: /EmbeddingRun2016_H/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016F_em
  process: emb_em
  key: /EmbeddingRun2016_F/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016G_em
  process: emb_em
  key: /EmbeddingRun2016_G/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True
- name: emb_2016H_em
  process: emb_em
  key: /EmbeddingRun2016_H/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

#- name: dy_ll_m10to50_madgraph
#  process: dy_ll_m10to50
#  key: /DYJetsToLL_M-10to50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v1/MINIAODSIM
#  is_data: False
#  aux:
#    dbs_instance: prod/global

- name: dy_ll_m50_madgraph
  process: dy_ll_m50
  key: /DYJetsToLL_M-50_TuneCP5_13TeV-madgraphMLM-pythia8/RunIISummer20UL16MiniAODv2-106X_mcRun2_asymptotic_v17-v1/MINIAODSIM
  is_data: False
  aux:
    dbs_instance: prod/global


channels:

- name: et
  label: $\mathrm{e}\tau_{\mathrm{h}}$
  aux:
    triggers:
    - name: HLT_Ele25_eta2p1_WPTight_Gsf
    - name: HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1
    - name: HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau30

- name: mt
  label: $\mu\tau_{\\mathrm{h}}$
  aux:
    triggers:
    - name: HLT_IsoMu22
    - name: HLT_IsoTkMu22
    - name: HLT_IsoMu22_eta2p1
    - name: HLT_IsoTkMu22_eta2p1
    - name: HLT_IsoMu19_eta2p1_LooseIsoPFTau20_SingleL1

- name: tt
  label: $\tau_{\\mathrm{h}}\\tau_{\\mathrm{h}}$
  aux:
    triggers:
    - name: HLT_DoubleMediumIsoPFTau35_Trk1_eta2p1_Reg
    - name: HLT_DoubleMediumCombinedIsoPFTau35_Trk1_eta2p1_Reg

#- name: em
#  label: $\mathrm{e}\mu$
#  aux:
#    triggers:
#    - name: HLT_IsoMu22
#    - name: HLT_IsoTkMu22
#    - name: HLT_IsoMu22_eta2p1
#    - name: HLT_IsoTkMu22_eta2p1
#    - name: HLT_Ele25_eta2p1_WPTight_Gsf
#    - name: HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL
#    - name: HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL
#    - name: HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
#    - name: HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ
