config:
  name: ul16preVFP_miniaod
  aux:
    cmssw:
      release: CMSSW_10_6_28_patch1
      arch: slc7_amd64_gcc700
      custom_packages_script: ${ETV_BASE_PATH}/scripts/cmssw_packages_embedding.sh


campaign:

  name: ul16preVFP_miniaod
  aux:
    era_name: "2016preVFP"


processes:

- name: emb
  label: $\\mu \\to \\tau$ embedded
  processes:
  - name: emb_et
  - name: emb_mt
  - name: emb_tt
  - name: emb_em

- name: dy_ll
  label: Drell-Yan ($\\ell\\ell$)
  processes:
  - name: dy_ll_m10to50
  - name: dy_ll_m50


datasets:

- name: emb_2016B_ver1_et
  process: emb_et
  key: /EmbeddingRun2016-HIPM_B_ver1/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016B_ver2_et
  process: emb_et
  key: /EmbeddingRun2016-HIPM_B_ver2/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016C_et
  process: emb_et
  key: /EmbeddingRun2016-HIPM_C/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016D_et
  process: emb_et
  key: /EmbeddingRun2016-HIPM_D/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016E_et
  process: emb_et
  key: /EmbeddingRun2016-HIPM_E/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016F_et
  process: emb_et
  key: /EmbeddingRun2016-HIPM_F/ElTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016B_ver1_mt
  process: emb_mt
  key: /EmbeddingRun2016-HIPM_B_ver1/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016B_ver2_mt
  process: emb_mt
  key: /EmbeddingRun2016-HIPM_B_ver2/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016C_mt
  process: emb_mt
  key: /EmbeddingRun2016-HIPM_C/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016D_mt
  process: emb_mt
  key: /EmbeddingRun2016-HIPM_D/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016E_mt
  process: emb_mt
  key: /EmbeddingRun2016-HIPM_E/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016F_mt
  process: emb_mt
  key: /EmbeddingRun2016-HIPM_F/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016B_ver1_tt
  process: emb_tt
  key: /EmbeddingRun2016-HIPM_B_ver1/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016B_ver2_tt
  process: emb_tt
  key: /EmbeddingRun2016-HIPM_B_ver2/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016C_tt
  process: emb_tt
  key: /EmbeddingRun2016-HIPM_C/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016D_tt
  process: emb_tt
  key: /EmbeddingRun2016-HIPM_D/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016E_tt
  process: emb_tt
  key: /EmbeddingRun2016-HIPM_E/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016F_tt
  process: emb_tt
  key: /EmbeddingRun2016-HIPM_F/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016B_ver1_em
  process: emb_em
  key: /EmbeddingRun2016-HIPM_B_ver1/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016B_ver2_em
  process: emb_em
  key: /EmbeddingRun2016-HIPM_B_ver2/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016C_em
  process: emb_em
  key: /EmbeddingRun2016-HIPM_C/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016D_em
  process: emb_em
  key: /EmbeddingRun2016-HIPM_D/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016E_em
  process: emb_em
  key: /EmbeddingRun2016-HIPM_E/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True

- name: emb_2016F_em
  process: emb_em
  key: /EmbeddingRun2016-HIPM_F/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
  is_data: True
  aux:
    dbs_instance: prod/phys03
    is_emb: True


channels:

- name: et
  label: $\\mathrm{{e}}\\tau_{{\\mathrm{{h}}}}$
  aux:
    triggers:
    - name: HLT_Ele25_eta2p1_WPTight_Gsf
    - name: HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau20_SingleL1
    - name: HLT_Ele24_eta2p1_WPLoose_Gsf_LooseIsoPFTau30

- name: mt
  label: $\\mu\\tau_{{\\mathrm{{h}}}}$
  aux:
    triggers:
    - name: HLT_IsoMu22
    - name: HLT_IsoTkMu22
    - name: HLT_IsoMu22_eta2p1
    - name: HLT_IsoTkMu22_eta2p1
    - name: HLT_IsoMu19_eta2p1_LooseIsoPFTau20_SingleL1

- name: tt
  label: $\\tau_{{\\mathrm{{h}}}}\\tau_{{\\mathrm{{h}}}}$
  aux:
    triggers:
    - name: HLT_DoubleMediumIsoPFTau35_Trk1_eta2p1_Reg
    - name: HLT_DoubleMediumCombinedIsoPFTau35_Trk1_eta2p1_Reg

- name: em
  label: $\\mathrm{{e}}\\mu$
  aux:
    triggers:
    - name: HLT_IsoMu22
    - name: HLT_IsoTkMu22
    - name: HLT_IsoMu22_eta2p1
    - name: HLT_IsoTkMu22_eta2p1
    - name: HLT_Ele25_eta2p1_WPTight_Gsf
    - name: HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL
    - name: HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL
    - name: HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ
    - name: HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ
