dbs_id: 3098903
dbs_instance: prod/phys03
key: /EmbeddingRun2016_F/MuTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
lfns:
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/MuTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/22008caa-714b-455e-8a4f-c7c113eb5aa3.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/MuTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/23f56cf8-2ee2-4583-ad6c-c20d53bf7b54.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/MuTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/258ac3d1-790c-4099-96a8-36fe1845b13a.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/MuTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/2a0aada0-f468-4057-a6ea-fb7c5ad2ee25.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/MuTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/5bae82a3-aa54-4128-9624-d48d59907952.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/MuTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/5f84e98d-907c-4a5d-8c24-c5e2fb67d789.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/MuTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/6ead27f4-a063-42bc-be4f-b80114b3c14f.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/MuTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/71f431ef-4a60-432e-9ec1-95757c405b1f.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/MuTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/d29cb961-1849-456c-96f5-9e1541ee0d35.root
n_events: 295786
n_files: 9
