dbs_id: 3098905
dbs_instance: prod/phys03
key: /EmbeddingRun2016_F/TauTauFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
lfns:
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/TauTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/70b094f1-0fec-4232-91ad-8aa09e586a49.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/TauTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/81e3fd89-6ecd-4b21-b58b-f7ba5ae652f6.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/TauTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/8b74277f-7e1e-44e5-a60d-4050f32b5946.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/TauTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/8bc9ec16-ad75-4e66-908a-71d9628f79cf.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/TauTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/a7319892-3414-41fb-ba2a-bec827bd504f.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/TauTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/b4557240-71a7-4587-81fb-9e075bc5aa49.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/TauTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/b5d1531e-3f5a-4ccb-a29f-80d1ca189786.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/TauTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/e4de75c9-1582-4792-99b1-98fdbb12faf3.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/TauTauFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/eebc0482-7ffe-4bab-96d2-408ea25d7b33.root
n_events: 263765
n_files: 9
