dbs_id: 3098900
dbs_instance: prod/phys03
key: /EmbeddingRun2016_F/ElMuFinalState-inputDoubleMu_106X_ULegacy_miniAOD-v1/USER
lfns:
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/ElMuFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/033dda5e-33af-432c-b515-ec0248378cda.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/ElMuFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/044732da-827c-4d39-be06-c5a4c80c9718.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/ElMuFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/27cdf52d-eb2b-45a5-8e1e-eddf08ca3e25.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/ElMuFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/6572318a-704f-4497-9cfa-46356de36edc.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/ElMuFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/77ce318e-41e6-4654-8bbe-ccdfb760dd39.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/ElMuFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/7fdc1160-3e8a-4495-9174-7356da767c16.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/ElMuFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/b091be69-d916-4502-96f4-0b7700dbd058.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/ElMuFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/c0e8ccb7-13cd-47e3-b055-8032cf4cc597.root
- /store/group/rucio/pog_tau_group/ul_embedding/large_miniAOD_v2/ElMuFinalState/EmbeddingRun2016_F/MINIAOD/inputDoubleMu_106X_ULegacy_miniAOD-v1/0000/c524ea62-2368-423e-8aa4-d139afbe49c4.root
n_events: 330129
n_files: 9
